# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_day_weekday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='day',
            name='procrastination_visits',
            field=models.IntegerField(default=0),
        ),
    ]
