# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20170504_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='procrastination_mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='day',
            name='productivity_mins',
            field=models.IntegerField(default=0),
        ),
    ]
