# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(default='', max_length=32),
        ),
    ]
