# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pages_day',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pages_week',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='top_100_words',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='word_count',
            field=models.TextField(default='{}'),
        ),
    ]
