# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-04 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_customuser_tracking_on'),
        ('authentication', '0004_auto_20170302_0659'),
    ]

    operations = [
    ]
