# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-21 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_20170304_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='offset',
            field=models.FloatField(default=4.0),
        ),
    ]
