# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-04 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_offset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pages_day',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pages_week',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='top_100_words',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='word_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='procrastination_sites',
            field=models.TextField(default="['www.facebook.com', 'www.twitter.com', 'www.instagram.com', 'www.netflix.com', 'play.hbogo.com', 'www.hbogo.com', 'www.pinterest.com', 'www.reddit.com']"),
        ),
    ]
