# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(blank=True, to='history.Category'),
        ),
    ]
