# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20161017_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('base_url', models.CharField(max_length=1000)),
                ('favicon', models.CharField(blank=True, default='', max_length=1000)),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Domain')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Page')),
            ],
            options={
                'ordering': ('visited',),
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tab_id', models.IntegerField()),
                ('closed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='domain',
            name='tab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Tab'),
        ),
    ]
