# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20161030_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='opened_from_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.Domain'),
        ),
    ]
