# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_merge_20170107_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('created',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ('visited',), 'verbose_name': 'pagevisit', 'verbose_name_plural': 'pagevisits'},
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
