# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0010_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
