# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0013_auto_20170206_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
