# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_session_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='No Title', max_length=50),
        ),
    ]
