# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0016_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#F8A055', max_length=7),
        ),
    ]
