# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0017_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='blacklisted',
        ),
        migrations.AddField(
            model_name='page',
            name='domain',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
