# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-16 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0018_auto_20170213_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='s3',
            field=models.CharField(default='https://s3.us-east-2.amazonaws.com/hindsite-production/404_not_found.html', max_length=10000),
        ),
    ]
