# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0019_pagevisit_s3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='html',
        ),
    ]
