# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-07 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0020_remove_pagevisit_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='preview',
            field=models.CharField(default='https://s3.us-east-2.amazonaws.com/hindsite-production/default-image.jpg', max_length=10000),
        ),
    ]
