# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-27 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0023_auto_20170525_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_pages',
            field=models.IntegerField(default=0),
        ),
    ]
