# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0023_page_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='keywords',
            new_name='topwords',
        ),
    ]
