# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-25 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0024_auto_20170525_2210'),
        ('history', '0024_auto_20170525_2206'),
    ]

    operations = [
    ]
